definitions:
  models.PaginatedLyrics:
    properties:
      lyricsPage:
        type: integer
      text:
        type: string
    type: object
  models.PaginatedSongData:
    properties:
      currentPage:
        type: integer
      entries:
        items:
          $ref: '#/definitions/models.SongDataWithID'
        type: array
    type: object
  models.SongData:
    properties:
      group:
        type: string
      lyrics:
        type: string
      song:
        type: string
    type: object
  models.SongDataWithID:
    properties:
      group:
        type: string
      id:
        type: integer
      lyrics:
        type: string
      song:
        type: string
    type: object
info:
  contact: {}
  title: Music Library
  version: 0.0.1
paths:
  /library:
    get:
      description: get paginated song data with optional flitration by group, song,
        lyrics or page
      parameters:
      - description: fliter by group
        in: query
        name: group
        type: string
      - description: fliter by song
        in: query
        name: song
        type: string
      - description: fliter by lyrics
        in: query
        name: lyrics
        type: string
      - description: fliter by page
        in: query
        name: page
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.PaginatedSongData'
            type: array
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Get music library
  /songs:
    delete:
      consumes:
      - application/json
      description: delete song data
      parameters:
      - description: id of a song
        in: query
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Delete song
    get:
      consumes:
      - application/json
      description: get paginated lyrics data for a song
      parameters:
      - description: id of a song
        in: query
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.PaginatedLyrics'
            type: array
                  responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.PaginatedLyrics'
            type: object
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Get lyrics
    post:
      consumes:
      - application/json
      description: add song to the server
      parameters:
      - description: artist and song title, lyrics are optional
        in: body
        name: song
        required: true
        schema:
          $ref: '#/definitions/models.SongData'
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Add song
    put:
      consumes:
      - application/json
      description: edit song data
      parameters:
      - description: id of a song
        in: query
        name: id
        required: true
        type: string
      - description: artist and song title, lyrics are optional
        in: body
        name: song
        required: true
        schema:
          $ref: '#/definitions/models.SongData'
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Edit song
swagger: "2.0"
