definitions:
  models.FullSongData:
    properties:
      artist:
        type: string
      link:
        type: string
      lyrics:
        type: string
      releasedate:
        type: string
      song:
        type: string
    type: object
  models.NewSongData:
    properties:
      artist:
        type: string
      song:
        type: string
    type: object
  models.PaginatedLyrics:
    properties:
      page:
        type: integer
      text:
        type: string
    type: object
  models.PaginatedSongData:
    properties:
      entries:
        items:
          $ref: '#/definitions/models.FullSongData'
        type: array
      page:
        type: integer
    type: object
info:
  contact: {}
  title: Music Library
  version: 0.0.1
paths:
  /library:
    get:
      description: get paginated song data with optional flitration by artist, song,
        lyrics or page
      parameters:
      - description: fliter by artist
        in: query
        name: artist
        type: string
      - description: fliter by song
        in: query
        name: song
        type: string
      - description: fliter by lyrics
        in: query
        name: lyrics
        type: string
      - description: fliter by release date
        in: query
        name: releasedate
        type: string
      - description: fliter by link
        in: query
        name: link
        type: string
      - description: fliter by page
        in: query
        name: page
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.PaginatedSongData'
            type: array
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Get music library
  /songs:
    delete:
      consumes:
      - application/json
      description: delete song data
      parameters:
      - description: artist name
        in: query
        name: artist
        required: true
        type: string
      - description: song title
        in: query
        name: song
        required: true
        type: string
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Delete song
    get:
      consumes:
      - application/json
      description: get paginated lyrics data for a song
      parameters:
      - description: artist name
        in: query
        name: artist
        required: true
        type: string
      - description: song title
        in: query
        name: song
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.PaginatedLyrics'
            type: array
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Get lyrics
    post:
      consumes:
      - application/json
      description: add song to the server
      parameters:
      - description: artist name and song title
        in: body
        name: song
        required: true
        schema:
          $ref: '#/definitions/models.NewSongData'
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Add song
    put:
      consumes:
      - application/json
      description: edit song data
      parameters:
      - description: artist name
        in: query
        name: artist
        required: true
        type: string
      - description: song title
        in: query
        name: song
        required: true
        type: string
      - description: new artist name, song title, lyrics, release date, link. All fields are optional
        in: body
        name: song
        required: true
        schema:
          $ref: '#/definitions/models.FullSongData'
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Edit song
swagger: "2.0"
